// Generated by CoffeeScript 2.3.2
(function() {
  // Pattern
  // -------

  // Does the number `n` match the pattern `p`.

  // The pattern must consists of only:
  // - digits
  // - '?', '.' -- replace single of above
  // - '..', '...', '…' -- replace zero or more
  var pattern;

  module.exports = pattern = function(p) {
    p = p.replace(/\.\.|\.\.\.|…/g, '\\d*').replace(/\?|\./g, '\\d');
    return new RegExp(`^${p}$`);
  };

}).call(this);
